/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.edu.ijse.hotelmanagementsystem.views;

import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.edu.ijse.hotelmanagementsystem.controller.ControllerFactory;
import lk.edu.ijse.hotelmanagementsystem.controller.custom.ServiceController;
import lk.edu.ijse.hotelmanagementsystem.dto.ServiceDTO;
import lk.edu.ijse.hotelmanagementsystem.idgenerator.IDGenerator;

/**
 *
 * @author USER
 */
public class ManageServicesDetail extends javax.swing.JFrame {

    private ServiceController ctrlServ;
    private DefaultTableModel dtmServ;
    /**
     * Creates new form ViewCustomerDetail
     */
    public ManageServicesDetail() {
        initComponents();
        idGenerater();
        coman();
        setLocationRelativeTo(null);
        loadDataServ();
    }
    
    public void coman(){
        ctrlServ =(ServiceController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.SERVICE);
        dtmServ = (DefaultTableModel) tblServices.getModel();
        tblServices.getTableHeader().setFont(this.getFont().deriveFont(Font.BOLD));
    }
    
    private void loadDataServ() {

        dtmServ.setRowCount(0);
        try {
            ArrayList<ServiceDTO> allServi = ctrlServ.getAll();
            
            if (allServi == null) {
                return;
            }
            for (ServiceDTO serv : allServi) {
                
                Object[] rowData = {
                    serv.getSid(),
                    serv.getService_name(),
                    serv.getPrice()
                };
                dtmServ.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageServicesDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblServices = new javax.swing.JTable();
        lblStep8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtSID = new javax.swing.JTextField();
        txtServicesName = new javax.swing.JTextField();
        txtPrices = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblServices.setBackground(new java.awt.Color(240, 240, 240));
        tblServices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Services ID", "Service Name", "Prices"
            }
        ));
        tblServices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblServicesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblServices);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 860, 310));

        lblStep8.setBackground(new java.awt.Color(0, 0, 51));
        lblStep8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblStep8.setForeground(new java.awt.Color(255, 255, 255));
        lblStep8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStep8.setText("Manage Services");
        lblStep8.setOpaque(true);
        getContentPane().add(lblStep8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 500, 110, 30));

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 80, 30));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 110, 30));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, 110, 30));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 110, 30));

        txtSID.setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().add(txtSID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 250, 30));

        txtServicesName.setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().add(txtServicesName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 250, 30));

        txtPrices.setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().add(txtPrices, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 250, 30));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Prices");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 90, 30));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Services Name");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, 30));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Services ID");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 30));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 24, 890, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblServicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServicesMouseClicked
        tblClik();
    }//GEN-LAST:event_tblServicesMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loadReception();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        searchServices();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        updateServices();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        deleteServices();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        addServices();
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageServicesDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageServicesDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageServicesDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageServicesDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageServicesDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStep8;
    private javax.swing.JTable tblServices;
    private javax.swing.JTextField txtPrices;
    private javax.swing.JTextField txtSID;
    private javax.swing.JTextField txtServicesName;
    // End of variables declaration//GEN-END:variables

    private void loadReception() {
        new ReceptionMain().setVisible(true);
        this.dispose();
    }
    
    private void searchServices() {
        String fid = txtSID.getText();
        
        try{
            ServiceDTO facList = ctrlServ.search(fid);
            if (facList== null) {
                JOptionPane.showMessageDialog(this, "Services not found..");
            } else {
                txtSID.setText(facList.getSid());
                txtServicesName.setText(facList.getService_name());
                txtPrices.setText(""+facList.getPrice());
            }
        }catch(Exception e){
            Logger.getLogger(ManageServicesDetail.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    private void addServices() {
        
        String sid = txtSID.getText();
        String servName = txtServicesName.getText();
        Double price =  Double.parseDouble(txtPrices.getText());
       
        ServiceDTO fac = new ServiceDTO(sid, servName, price);
        try {
            boolean add = ctrlServ.add(fac);
            if (add) {
                JOptionPane.showMessageDialog(this, "Services Added Successfully");
            }else{
                JOptionPane.showMessageDialog(this, "Services Added Failed");
            }
        } catch (Exception e) {
        }
        loadDataServ();
    }
    
    public void deleteServices(){
        
        String fa = dtmServ.getValueAt(tblServices.getSelectedRow(), 0).toString();
        try {
            boolean deleted = ctrlServ.delete(fa);
        } catch (Exception ex) {
            
            Logger.getLogger(ManageServicesDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadDataServ();
    }
    
    public void updateServices(){
        
        String sid = txtSID.getText();
        String servName = txtServicesName.getText();
        Double price =  Double.parseDouble(txtPrices.getText());
        
        ServiceDTO fac = new ServiceDTO(sid, servName, price);
        try {
            boolean isUpdated = ctrlServ.update(fac);
            if (isUpdated) {
                JOptionPane.showMessageDialog( this,"Update Sucess");
            } else {
                JOptionPane.showMessageDialog( this,"Update SucessFully");
            }
            
        } catch (Exception e) {
            Logger.getLogger(ManageServicesDetail.class.getName()).log(Level.SEVERE, null, e);
        }
        loadDataServ();
    }
    private void tblClik() {
        
        int selectedRow = tblServices.getSelectedRow();
        String rid = tblServices.getValueAt(selectedRow, 0).toString();
        String name =tblServices.getValueAt(selectedRow,1).toString();
        String price =tblServices.getValueAt(selectedRow,2).toString();
        
        txtSID.setText(rid);
        txtServicesName.setText(name);
        txtPrices.setText(price);
    }
    
    public void idGenerater(){
        try {
            String id= IDGenerator.getNewID("service","sid", "S0");
            txtSID.setText(id);
        } catch (SQLException ex) {
            Logger.getLogger(ReceptionMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ReceptionMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
