/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.edu.ijse.hotelmanagementsystem.views;

import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.edu.ijse.hotelmanagementsystem.controller.ControllerFactory;
import lk.edu.ijse.hotelmanagementsystem.controller.custom.FacilityController;
import lk.edu.ijse.hotelmanagementsystem.dto.FacilityDTO;
import lk.edu.ijse.hotelmanagementsystem.idgenerator.IDGenerator;

/**
 *
 * @author USER
 */
public class ManageFacilityDetail extends javax.swing.JFrame {

    private FacilityController ctrlFac;
    private DefaultTableModel dtmFac;
    /**
     * Creates new form ViewCustomerDetail
     */
    public ManageFacilityDetail() {
        initComponents();
        coman();
        idGenerater();
        setLocationRelativeTo(null);
        loadDataFacility();
    }
    
    public void coman(){
        ctrlFac =(FacilityController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.FACILITY);
        dtmFac = (DefaultTableModel) tblFacility.getModel();
        tblFacility.getTableHeader().setFont(this.getFont().deriveFont(Font.BOLD));
    }
    
    private void loadDataFacility() {

        dtmFac.setRowCount(0);
        try {
            ArrayList<FacilityDTO> allFacility = ctrlFac.getAll();
            
            if (allFacility == null) {
                return;
            }
            for (FacilityDTO room : allFacility) {
                
                Object[] rowData = {
                    room.getFid(),
                    room.getFacility_Name(),
                    room.getPrices()
                };
                dtmFac.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageFacilityDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFacility = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtFacilityName = new javax.swing.JTextField();
        txtPrices = new javax.swing.JTextField();
        txtFID = new javax.swing.JTextField();
        lblStep8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnCansel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblFacility.setBackground(new java.awt.Color(204, 204, 204));
        tblFacility.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Facility ID", "Facility Name", "Prices"
            }
        ));
        tblFacility.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFacilityMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFacility);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 860, 300));

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 80, 30));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 110, 30));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 110, 30));
        getContentPane().add(txtFacilityName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 250, 30));
        getContentPane().add(txtPrices, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 250, 30));
        getContentPane().add(txtFID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 250, 30));

        lblStep8.setBackground(new java.awt.Color(0, 0, 51));
        lblStep8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblStep8.setForeground(new java.awt.Color(255, 255, 255));
        lblStep8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStep8.setText("Manage Facility");
        lblStep8.setOpaque(true);
        getContentPane().add(lblStep8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 30));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Prices");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 90, 30));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Facility ID");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 30));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Facility Name");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, 30));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, 110, 30));

        btnCansel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCansel.setText("Cancel");
        btnCansel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanselActionPerformed(evt);
            }
        });
        getContentPane().add(btnCansel, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 480, 110, 30));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 24, 890, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblFacilityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFacilityMouseClicked
        tblClik();
    }//GEN-LAST:event_tblFacilityMouseClicked

    private void btnCanselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanselActionPerformed
        loadReception();
    }//GEN-LAST:event_btnCanselActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        deleteFacility();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        searchFacility();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        addFacility();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        updateFacility();
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageFacilityDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageFacilityDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageFacilityDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageFacilityDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageFacilityDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCansel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStep8;
    private javax.swing.JTable tblFacility;
    private javax.swing.JTextField txtFID;
    private javax.swing.JTextField txtFacilityName;
    private javax.swing.JTextField txtPrices;
    // End of variables declaration//GEN-END:variables

    private void loadReception() {
        new ReceptionMain().setVisible(true);
        this.dispose();
    }
    
    private void searchFacility() {
        String fid = txtFID.getText();
        
        try{
            FacilityDTO facList = ctrlFac.search(fid);
            if (facList== null) {
                JOptionPane.showMessageDialog(this, "Facility not found..");
            } else {
                txtFID.setText(facList.getFid());
                txtFacilityName.setText(facList.getFacility_Name());
                txtPrices.setText(""+facList.getPrices());
            }
        }catch(Exception e){
            Logger.getLogger(ManageFacilityDetail.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    private void addFacility() {
        
        String fid = txtFID.getText();
        String FacilityName = txtFacilityName.getText();
        Double price =  Double.parseDouble(txtPrices.getText());
       
        FacilityDTO fac = new FacilityDTO(fid, FacilityName, price);
        try {
            boolean add = ctrlFac.add(fac);
            if (add) {
                JOptionPane.showMessageDialog(this, "Facility Added Successfully");
            }else{
                JOptionPane.showMessageDialog(this, "Facility Added Failed");
            }
        } catch (Exception e) {
        }
        loadDataFacility();
    }
    
    public void deleteFacility(){
        
        String fa = dtmFac.getValueAt(tblFacility.getSelectedRow(), 0).toString();
        try {
            boolean deleted = ctrlFac.delete(fa);
        } catch (Exception ex) {
            
            Logger.getLogger(ManageFacilityDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadDataFacility();
    }
    
    public void updateFacility(){
        
        String fid=txtFID.getText();
	String name=txtFacilityName.getText();
	Double prices=Double.parseDouble(txtPrices.getText());
        
        FacilityDTO fac = new FacilityDTO(fid, name, prices);
        try {
            boolean isUpdated = ctrlFac.update(fac);
            if (isUpdated) {
                JOptionPane.showMessageDialog( this,"Update Sucess");
            } else {
                JOptionPane.showMessageDialog( this,"Update SucessFully");
            }
            
        } catch (Exception e) {
            Logger.getLogger(ManageFacilityDetail.class.getName()).log(Level.SEVERE, null, e);
        }
        loadDataFacility();
    }
    private void tblClik() {
        
        int selectedRow = tblFacility.getSelectedRow();
        String rid = tblFacility.getValueAt(selectedRow, 0).toString();
        String name =tblFacility.getValueAt(selectedRow,1).toString();
        String price =tblFacility.getValueAt(selectedRow,2).toString();
        
        txtFID.setText(rid);
        txtFacilityName.setText(name);
        txtPrices.setText(price);
    }
    
    public void idGenerater(){
        try {
            String id= IDGenerator.getNewID("facility","fid", "F0");
            txtFID.setText(id);
        } catch (SQLException ex) {
            Logger.getLogger(ReceptionMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ReceptionMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
