/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.edu.ijse.hotelmanagementsystem.views;

import java.awt.Font;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lk.edu.ijse.hotelmanagementsystem.controller.ControllerFactory;
import lk.edu.ijse.hotelmanagementsystem.controller.custom.RegistrationController;
import lk.edu.ijse.hotelmanagementsystem.dto.RegistrationDTO;

/**
 *
 * @author USER
 */
public class ViewRegistrationDetail extends javax.swing.JFrame {

    private RegistrationController ctrlRegis;
    private DefaultTableModel dtmRegistration;
    /**
     * Creates new form ViewCustomerDetail
     */
    public ViewRegistrationDetail() {
        initComponents();
        coman();
        setLocationRelativeTo(null);
        loadDataRegistration();
    }
    
    public void coman(){
        ctrlRegis =(RegistrationController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.REGISTRATION);
        dtmRegistration = (DefaultTableModel) tblRegistration.getModel();
        tblRegistration.getTableHeader().setFont(this.getFont().deriveFont(Font.BOLD));
    }
    
    private void loadDataRegistration() {

        dtmRegistration.setRowCount(0);
        try {
            ArrayList<RegistrationDTO> allReg = ctrlRegis.getAll();
            
            if (allReg == null) {
                return;
            }
            for (RegistrationDTO regis : allReg) {
                
                Object[] rowData = {
                    regis.getReid(),
                    regis.getCid(),
                    regis.getCheckin(),
                    regis.getCheckout(),
                    regis.getNo_of_rooms(),
                    regis.getNo_of_adults(),
                    regis.getNo_of_children()
                };
                dtmRegistration.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(ViewRegistrationDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistration = new javax.swing.JTable();
        lblStep8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRegistration.setBackground(new java.awt.Color(204, 204, 204));
        tblRegistration.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Regis. ID", "Customer ID", "Chek In", "Chek Out", "No Of Room", "Adult Num.", "Child Num."
            }
        ));
        tblRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRegistrationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRegistration);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 860, 330));

        lblStep8.setBackground(new java.awt.Color(0, 0, 51));
        lblStep8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblStep8.setForeground(new java.awt.Color(255, 255, 255));
        lblStep8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStep8.setText("Registration Detail");
        lblStep8.setOpaque(true);
        getContentPane().add(lblStep8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 40));

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, 110, 30));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 890, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblRegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRegistrationMouseClicked
    }//GEN-LAST:event_tblRegistrationMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loadReception();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRegistrationDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRegistrationDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRegistrationDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRegistrationDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRegistrationDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStep8;
    private javax.swing.JTable tblRegistration;
    // End of variables declaration//GEN-END:variables

    private void loadReception() {
        new ReceptionMain().setVisible(true);
        this.dispose();
    }
}
