/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.edu.ijse.hotelmanagementsystem.views;

import java.awt.Font;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lk.edu.ijse.hotelmanagementsystem.controller.ControllerFactory;
import lk.edu.ijse.hotelmanagementsystem.controller.custom.FacilityController;
import lk.edu.ijse.hotelmanagementsystem.dto.FacilityDTO;

/**
 *
 * @author USER
 */
public class ViewFacilityDetail extends javax.swing.JFrame {

    private FacilityController ctrlFac;
    private DefaultTableModel dtmFac;
    /**
     * Creates new form ViewCustomerDetail
     */
    public ViewFacilityDetail() {
        initComponents();
        coman();
        setLocationRelativeTo(null);
        loadDataFacility();
    }
    
    public void coman(){
        ctrlFac =(FacilityController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.FACILITY);
        dtmFac = (DefaultTableModel) tblFacility.getModel();
        tblFacility.getTableHeader().setFont(this.getFont().deriveFont(Font.BOLD));
    }
    
    private void loadDataFacility() {

        dtmFac.setRowCount(0);
        try {
            ArrayList<FacilityDTO> allFacility = ctrlFac.getAll();
            
            if (allFacility == null) {
                return;
            }
            for (FacilityDTO room : allFacility) {
                
                Object[] rowData = {
                    room.getFid(),
                    room.getFacility_Name(),
                    room.getPrices()
                };
                dtmFac.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(ViewFacilityDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFacility = new javax.swing.JTable();
        lblStep8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblFacility.setBackground(new java.awt.Color(204, 204, 204));
        tblFacility.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Facility ID", "Facility Name", "Prices"
            }
        ));
        tblFacility.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFacilityMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFacility);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 860, 330));

        lblStep8.setBackground(new java.awt.Color(0, 0, 51));
        lblStep8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblStep8.setForeground(new java.awt.Color(255, 255, 255));
        lblStep8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStep8.setText("Facility Detail");
        lblStep8.setOpaque(true);
        getContentPane().add(lblStep8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 30));

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, 110, 30));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 24, 890, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblFacilityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFacilityMouseClicked
    }//GEN-LAST:event_tblFacilityMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loadReception();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFacilityDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFacilityDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFacilityDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFacilityDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFacilityDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStep8;
    private javax.swing.JTable tblFacility;
    // End of variables declaration//GEN-END:variables

    private void loadReception() {
        new ReceptionMain().setVisible(true);
        this.dispose();
    }
}
